<footer class="footer">
        <div class="content">
            <div class="social-networks social-networks-home">
                <a href="https://www.facebook.com/semanacomp" target="_blank"><i class="fa fa-facebook"></i></a>
                <a href="https://www.youtube.com/user/SEMCOMPUFBA" target="_blank"><i class="fa fa-youtube"></i></a>
                <a href="https://twitter.com/Semcompufba" target="_blank"><i class="fa fa-twitter"></i></a>
            </div>
            <ul class="footer">
                <a href="index.php"><li>Home</li></a>
                <a href="sobre.php"><li>A SEMCOMP</li></a>
                <a href="programacao.php"><li>Programação Geral</li></a>
                <a href=""><li>Minicursos</li></a>
                <a href=""><li>Maratona de Programação</li></a>
                <a href=""><li>Painel de Startups</li></a>
                <a href=""><li>Call for Papers</li></a>
                <a href="contact.php"><li>Contato</li></a>
                <a href=""><li>Inscreva-se</li></a>
            </ul>
            <h4>Realização</h4>
            <div class="col-lg-4 col-lg-offset-2">
               <a  class="link-info" href="http://www.infojr.com.br" target="_blank">
                <img class="logo-info" src="assets/images/info.png" alt="">
                   <span>www.infojr.com.br</span></a>
            </div>
            <div class="col-lg-4">
                <p class="description-info">Empresa Júnior de Informática da Universidade Federal da Bahia foi fundada em 26 de Janeiro de 1998, formada por alunos dos cursos de Computação, a empresa busca através de atividades teóricas e práticas, complementar a grade curricular.</p>
            </div>
            <p class="copyright">© Copyright 2015, Semana da Computação da UFBA. Todos os direitos reservados. Contato: contato@semcomp.com.br</p>
        </div>
</footer>
<script src="vendors/jquery/jquery-2.1.4.min.js"></script>
<script src="vendors/jquery/jquery-numscroller-1.0.js"></script>
<script src="vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/js/application.js"></script>
<script src="https://maps.googleapis.com/maps/api/js"></script>
