<footer class="footer">
        <div class="social-networks social-networks-home">
            <a href="https://www.facebook.com/semanacomp" target="_blank"><i class="fa fa-facebook"></i></a>
            <a href="https://www.youtube.com/user/SEMCOMPUFBA" target="_blank"><i class="fa fa-youtube"></i></a>
            <a href="https://twitter.com/Semcompufba" target="_blank"><i class="fa fa-twitter"></i></a>
        </div>
        <h4>Realização</h4>
        <div class="col-lg-2 col-lg-offset-4">
           <a  class="link-info" href="http://www.infojr.com.br" target="_blank">
            <img class="logo-info" src="assets/images/info.png" alt="">
               <p>www.infojr.com.br</p></a>
        </div>
        <div class="col-lg-4">
            <p class="description-info">Empresa Júnior de Informática da Universidade Federal da Bahia foi fundada em 26 de Janeiro de 1998, formada por alunos dos cursos de Computação, a empresa busca através de atividades teóricas e práticas, complementar a grade curricular. O trabalho desenvolvido ao longo desses anos é a motivação necessária para continuar prestando serviços cada vez mais desafiantes e que tragam impacto para a sociedade.</p>
        </div>
        <ul class="footer">
            <a href="index.php"><li>HOME</li></a> -
            <a href="sobre.php"><li>A SEMCOMP</li></a> -
            <a href=""><li class="links-responsive">PROGRAMAÇÃO GERAL</li></a> -
            <a href=""><li class="links-responsive">MINICURSOS</li></a> -
            <a href=""><li class="links-responsive">MARATONA DE PROGRAMAÇÃO</li></a> -
            <a href=""><li class="links-responsive">PAINEL DE STARTUPS</li></a> -
            <a href=""><li class="links-responsive">CALL FOR PAPERS</li></a> -
            <a href="contact.php"><li>CONTATO</li></a> -
            <a href=""><li>INSCREVA-SE</li></a>
        </ul>
        <p>© Copyright 2015, Semana da Computação da UFBA. Todos os direitos reservados. Contato: contato@semcomp.com</p>
</footer>
<script src="vendors/jquery/jquery-2.1.4.min.js"></script>
<script src="vendors/jquery/jquery-numscroller-1.0.js"></script>
<script src="vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/js/application.js"></script>
