<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<link rel="stylesheet" href="assets/stylesheets/application.css">
<link rel="stylesheet" href="vendors/bootstrap/css/bootstrap.min.css">
<link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="vendors/font-awesome-4.3.0/css/font-awesome.min.css">
