<nav>
   <div class="logo"><img src="assets/images/logo.png" alt=""></div>
   <button id="toggle" class="btn btn-menu"><i class="fa fa-bars"></i></button>
    <ul>
        <li class="nav">HOME</li>
        <li class="nav">A SEMCOMP</li>
        <li class="nav" id="dropdown">PROGRAMAÇÃO <i class="fa fa-chevron-down"></i>
            <ul class="programming">
                <li class="btn-programming"><i class="fa fa-table rotate"></i><p> HORÁRIOS</p></li>
                <li class="btn-programming"><i class="fa fa-trophy rotate"></i><p> MARATONA</p></li>
                <li class="btn-programming"><i class="fa fa-briefcase rotate"></i><p> STARTUPS</p></li>
                <li class="btn-programming"><i class="fa fa-gamepad rotate"></i><p> GAMES</p></li>
            </ul>
        </li>
        <li class="nav">CONTATO</li>
        <li class="nav rotate">INSCREVA-SE</li>
    </ul>
</nav>