<nav>
    <div class="nav-wrapper">
       <div class="logo"><img src="assets/images/marca_semcomp_2015_horizontal_colorida_fundo-escuro.png"alt=""></div>
       <button id="toggle" class="btn btn-menu"><i class="fa fa-bars"></i></button>
        <ul>
            <li class="nav"><a href="index.php">HOME</a></li>
            <li class="nav"><a href="sobre.php">A SEMCOMP</a></li>
            <li class="nav" id="dropdown"><a>PROGRAMAÇÃO <i class="fa fa-chevron-down"></i></a>
            </li>
            <li class="nav"><a href="contact.php">CONTATO</a></li>
            <li class="nav"><a href="">INSCREVA-SE</a></li>
        </ul>
    </div>
    <ul class="programming">
        <li class="btn-programming">PROGRAMAÇÃO GERAL</li>
        <li class="btn-programming">MINICURSOS</li>
        <li class="btn-programming">MARATONA DE PROGRAMAÇÃO</li>
        <li class="btn-programming">STARTUPS</li>
        <li class="btn-programming">CALL FOR PAPERS</li>
    </ul>
</nav>
