<nav>
   <div class="logo"><img src="assets/images/logo.png" alt=""></div>
   <i id="toggle" class="fa fa-bars"></i>
    <ul>
        <li>HOME</li>
        <li>A SEMCOMP</li>
        <li id="dropdown">PROGRAMAÇÃO <i class="fa fa-chevron-down"></i>
            <ul class="programming">
                <li><i class="fa fa-table"></i><p>HORÁRIOS</p></li>
                <li><i class="fa fa-trophy"></i><p>MARATONA</p></li>
                <li><i class="fa fa-briefcase"></i><p>STARTUPS</p></li>
                <li><i class="fa fa-gamepad"></i><p>GAMES</p></li>
            </ul>
        </li>
        <li>CONTATO</li>
        <li class="bg1">INSCREVA-SE</li>
    </ul>
</nav>